import test from 'node:test';
import assert from 'node:assert/strict';
import {createFighter,separateBodies,stepSkirmish,chargeReady,CHARGE} from '../js/three-demo/combat-model.js';
const run=(units,seconds,dt=1/60)=>{const events=[];for(let t=0;t<seconds-1e-8;t+=dt)events.push(...stepSkirmish(units,dt,true));return events;};
test('coincident infantry and horses separate by their real body radii and stay separated',()=>{const units=Array.from({length:16},(_,i)=>createFighter(i,i%2?'red':'blue',i%4?'infantry':'cavalry',0,0));separateBodies(units,100);for(let i=0;i<units.length;i++)for(let j=i+1;j<units.length;j++)assert.ok(Math.hypot(units[i].x-units[j].x,units[i].z-units[j].z)>=units[i].radius+units[j].radius-.005);});
test('stationary cavalry touching infantry cannot produce charge impacts',()=>{const horse=createFighter(0,'red','cavalry',0,0),foot=createFighter(1,'blue','infantry',2.2,0);const events=run([horse,foot],2);assert.equal(events.filter(e=>e.type==='charge').length,0);assert.ok(foot.hp<100);});
test('actual long forward run causes one first impact, knockback, cooldown and visible charge event',()=>{const horse=createFighter(0,'red','cavalry',-8,0),foot=createFighter(1,'blue','infantry',4,0);foot.target={x:4,z:0};const events=run([horse,foot],4);const hits=events.filter(e=>e.type==='charge'&&e.first);assert.equal(hits.length,1);assert.ok(horse.chargeCooldown>0);assert.ok(foot.hp<=100-CHARGE.damage);assert.ok(hits[0].nx>.9);});
test('heading reversal and separation displacement cannot manufacture run-up',()=>{const horse=createFighter(0,'red','cavalry',0,0),foot=createFighter(1,'blue','infantry',-2.2,0);horse.runup=5;horse.speed=4.8;const events=stepSkirmish([horse,foot],1/60,true);assert.equal(events.filter(e=>e.type==='charge').length,0);assert.equal(horse.runup,0);horse.runup=0;separateBodies([horse,foot]);assert.equal(horse.runup,0);assert.equal(chargeReady(horse,foot),false);});
test('dead bodies no longer constrain live bodies and death event happens once',()=>{const a=createFighter(0,'red','infantry',0,0),b=createFighter(1,'blue','infantry',1.25,0);b.hp=1;const events=run([a,b],3);assert.equal(events.filter(e=>e.type==='death'&&e.unit===b).length,1);const before={x:a.x,z:a.z};b.x=a.x;b.z=a.z;separateBodies([a,b]);assert.deepEqual({x:a.x,z:a.z},before);});
test('30 and 60 Hz both consume the run-up once and never reuse first impact in melee',()=>{for(const dt of [1/30,1/60]){const horse=createFighter(0,'red','cavalry',-8,0),foot=createFighter(1,'blue','infantry',4,0);foot.target={x:4,z:0};const events=run([horse,foot],5,dt);assert.equal(events.filter(e=>e.type==='charge'&&e.first).length,1);assert.equal(foot.hp,36);assert.equal(events.filter(e=>e.type==='hit'&&e.from===horse).length,2);}});

test('default mixed 32-fighter battle has impacts, a winner, and no body penetration',()=>{
 const units=[];for(const team of ['red','blue']){const side=team==='red'?-1:1;for(let i=0;i<12;i++)units.push(createFighter(units.length,team,'infantry',side*(8+Math.floor(i/4)*1.2),(i%4-1.5)*1.35));for(let i=0;i<4;i++)units.push(createFighter(units.length,team,'cavalry',side*(10.8+i%2*3.1),5.5+Math.floor(i/2)*3.1));}
 separateBodies(units);let charges=0,winner=false;for(let frame=0;frame<3600;frame++){charges+=stepSkirmish(units,1/60,true).filter(e=>e.type==='charge').length;const alive=units.filter(u=>u.hp>0);for(let i=0;i<alive.length;i++)for(let j=i+1;j<alive.length;j++)assert.ok(Math.hypot(alive[i].x-alive[j].x,alive[i].z-alive[j].z)>=alive[i].radius+alive[j].radius-.005);if(!alive.some(u=>u.team==='red')||!alive.some(u=>u.team==='blue')){winner=true;break;}}assert.ok(charges>0);assert.ok(winner);
});

test('spent charge momentum cannot damage a stationary side contact as another impact',()=>{const horse=createFighter(0,'red','cavalry',0,0),foot=createFighter(1,'blue','infantry',.1,1.2);Object.assign(horse,{heading:Math.PI/2,pierceTime:.7,momentum:.5,chargeCooldown:5,speed:0});const events=stepSkirmish([horse,foot],1/60,true);assert.equal(events.filter(e=>e.type==='charge').length,0);assert.equal(foot.hp,100);});

test('an edge kill cannot carry a lone horse off the battlefield',()=>{const horse=createFighter(0,'red','cavalry',16,0),foot=createFighter(1,'blue','infantry',17,0);Object.assign(horse,{runup:5,speed:4.8});foot.hp=1;run([horse,foot],2);assert.ok(horse.x<=17&&horse.x>=-17&&horse.z<=13&&horse.z>=-13);assert.equal(horse.pierceTime,0);assert.equal(horse.runup,0);});
